name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.100

    - name: Build
      run: dotnet build --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.100

    - name: Deploy
      run: |
        # Add your deployment steps here
        # For example, deploy to a server, a container, or a cloud platform

# Add more jobs or steps as needed for your specific deployment process
